### PR TITLE
Updated filename reference

### PR DESCRIPTION
**Pull request by vanerp**
updated js/splashingimages.js to js/SplashingImages.js in SplashingImagesAsset.php to fix errors on case-senstive file systems

### CODE REVIEW

**Comment by dennisfrank** [comment]
@janhenckens Could you merge this PR (or #6)? I run into the same error. It works locally on my case-insensitive macOS file system but not on my Ubuntu server. Thanks!

**Comment by janhenckens** [comment]
Oops, missed this @vanerp @dennisfrank! Will merge & release tonight!

**Comment by dennisfrank** [comment]
Thank you @janhenckens! :smiley:

**Comment by janhenckens** [comment]
Merge and released, should be in the plugin store any moment now!

**Pull request merged**
