### PR TITLE
Missing settings model in search action

### PR DESCRIPTION
**Pull request by KevinBeckers**

### CODE REVIEW

**Comment by KevinBeckers** [comment]
Fixed Two bugs #1  / #3

**Comment by janhenckens** [comment]
Thanks for catching these. Will merge & result asap!

Cheers
Jan.

**Comment by KevinBeckers** [comment]
No problem happy to help!

**Comment by janhenckens** [comment]
I released version 1.0.1 last night with these fixes, should be out in the plugin store :)

**Pull request merged**
